export const ENDPOINTS = {
  BASE: process.env.REACT_APP_API_URL!,
  STALLS: 'stalls/',
  PRODUCTS: 'products/',
  SEARCH: 'search/',
  HAWKERS: 'hawkercentres/',
  REGISTER: 'register/',
  LOGIN: 'login/',
  REVIEWS: 'reviews/',
  CATEGORIES: 'categories/',
  LOCATIONS: 'regions/',
  FAVOURITES: 'favourites/',
  ALL_SECURITY_QUESTIONS: 'securityQuestions',
  USER_ANSWERS: 'userAnswers/',
  USER_ANSWERS_VALIDATE: 'userAnswers/validate',
};
