export const ENDPOINTS = {
  BASE: 'https://dk-api-21.herokuapp.com/',
  STALLS: 'stalls/',
  PRODUCTS: 'products/',
  SEARCH: 'search/',
  HAWKERS: 'hawkercentres/',
  REGISTER: 'register/',
  LOGIN: 'login/',
  REVIEWS: 'reviews/',
  CATEGORIES: 'categories/',
  LOCATIONS: 'regions/',
  FAVOURITES: 'favourites/',
  ALL_SECURITY_QUESTIONS: 'securityQuestions/all',
  USER_ANSWERS: 'userAnswers/',
  USER_ANSWERS_VALIDATE: 'userAnswers/validate',
};
