name: Deploy to Google Cloud Storage

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy-gae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build:production

      - name: Set up cloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Storage
        run: gsutil rsync -R build gs://${{ secrets.GCS_PRODUCTION_BUILD_BUCKET }}
